
import java.awt.Color;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mi bodega poncitlan
 */
public class Pre_examen extends javax.swing.JFrame {

    public class Izquierda implements Runnable {
    Thread t;
    public void run() {
    Color c=Jp1.getBackground();
    Jp1.setBackground(Jp2.getBackground());
    Jp2.setBackground(Jp3.getBackground());
    Jp3.setBackground(Jp4.getBackground());
    Jp4.setBackground(c); 
        }
    }
    /**
     * Creates new form Pre_examen
     */
    public Pre_examen() {
        initComponents();
        int[] cuenta;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jp1 = new javax.swing.JPanel();
        Jp2 = new javax.swing.JPanel();
        Jp4 = new javax.swing.JPanel();
        Jp3 = new javax.swing.JPanel();
        BIzquierda = new javax.swing.JButton();
        BDerecha = new javax.swing.JButton();
        CBIzquierda = new javax.swing.JCheckBox();
        CBDerecha = new javax.swing.JCheckBox();
        JBGira = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Jp1.setBackground(new java.awt.Color(153, 0, 153));
        Jp1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout Jp1Layout = new javax.swing.GroupLayout(Jp1);
        Jp1.setLayout(Jp1Layout);
        Jp1Layout.setHorizontalGroup(
            Jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        Jp1Layout.setVerticalGroup(
            Jp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Jp2.setBackground(new java.awt.Color(0, 0, 153));
        Jp2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout Jp2Layout = new javax.swing.GroupLayout(Jp2);
        Jp2.setLayout(Jp2Layout);
        Jp2Layout.setHorizontalGroup(
            Jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        Jp2Layout.setVerticalGroup(
            Jp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Jp4.setBackground(new java.awt.Color(255, 51, 204));
        Jp4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout Jp4Layout = new javax.swing.GroupLayout(Jp4);
        Jp4.setLayout(Jp4Layout);
        Jp4Layout.setHorizontalGroup(
            Jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        Jp4Layout.setVerticalGroup(
            Jp4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Jp3.setBackground(new java.awt.Color(255, 0, 0));
        Jp3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        javax.swing.GroupLayout Jp3Layout = new javax.swing.GroupLayout(Jp3);
        Jp3.setLayout(Jp3Layout);
        Jp3Layout.setHorizontalGroup(
            Jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        Jp3Layout.setVerticalGroup(
            Jp3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        BIzquierda.setText("Izquierda");
        BIzquierda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BIzquierdaMouseClicked(evt);
            }
        });
        BIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIzquierdaActionPerformed(evt);
            }
        });

        BDerecha.setText("Derecha");
        BDerecha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BDerechaMouseClicked(evt);
            }
        });

        CBIzquierda.setText("Izquierda");
        CBIzquierda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBIzquierdaActionPerformed(evt);
            }
        });

        CBDerecha.setText("Derecha");
        CBDerecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CBDerechaActionPerformed(evt);
            }
        });

        JBGira.setText("GIRA");
        JBGira.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBGiraMouseClicked(evt);
            }
        });

        jButton2.setText("PARA");
        jButton2.setActionCommand("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Jp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(48, 48, 48)
                        .addComponent(BIzquierda))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(BDerecha)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CBIzquierda)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(JBGira)
                                .addComponent(CBDerecha)
                                .addComponent(jButton2)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jp3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jp2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Jp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BDerecha)
                        .addGap(18, 18, 18)
                        .addComponent(BIzquierda)))
                .addGap(12, 12, 12)
                .addComponent(CBIzquierda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CBDerecha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JBGira)
                        .addGap(29, 29, 29)
                        .addComponent(jButton2))
                    .addComponent(Jp4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Jp3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIzquierdaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BIzquierdaActionPerformed

    private void BDerechaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BDerechaMouseClicked
      Color c=Jp4.getBackground();
      Jp4.setBackground(Jp3.getBackground());
      Jp3.setBackground(Jp2.getBackground());
      Jp2.setBackground(Jp1.getBackground());
      Jp1.setBackground(c);
    }//GEN-LAST:event_BDerechaMouseClicked

    private void BIzquierdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BIzquierdaMouseClicked
    Color c=Jp1.getBackground();
    Jp1.setBackground(Jp2.getBackground());
    Jp2.setBackground(Jp3.getBackground());
    Jp3.setBackground(Jp4.getBackground());
    Jp4.setBackground(c);        // TODO add your handling code here:
    }//GEN-LAST:event_BIzquierdaMouseClicked

    private void CBIzquierdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBIzquierdaActionPerformed
    if( CBIzquierda.isSelected() ){ 
        CBDerecha.setSelected(false);    
    }
        
        
    }//GEN-LAST:event_CBIzquierdaActionPerformed

    private void CBDerechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CBDerechaActionPerformed
    if( CBDerecha.isSelected() ){ 
        CBIzquierda.setSelected(false);    
    }
    }//GEN-LAST:event_CBDerechaActionPerformed

    private void JBGiraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBGiraMouseClicked
     if( CBDerecha.isSelected() ){ 
        Thread t = new Thread( );  
        t.start();
         try {
            Thread.currentThread().sleep( 1000 );
        }catch( InterruptedException e ){}
    }
    }//GEN-LAST:event_JBGiraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pre_examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pre_examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pre_examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pre_examen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pre_examen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BDerecha;
    private javax.swing.JButton BIzquierda;
    private javax.swing.JCheckBox CBDerecha;
    private javax.swing.JCheckBox CBIzquierda;
    private javax.swing.JButton JBGira;
    private javax.swing.JPanel Jp1;
    private javax.swing.JPanel Jp2;
    private javax.swing.JPanel Jp3;
    private javax.swing.JPanel Jp4;
    private javax.swing.JButton jButton2;
    // End of variables declaration//GEN-END:variables
}
