/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package holamundo;

import java.awt.Color;

/**
 *
 * @author mi bodega poncitlan
 */
public class IHola extends javax.swing.JFrame {

    /**
     * Creates new form IHola
     */
    public IHola() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Eti1 = new javax.swing.JLabel();
        JB_Rojo = new javax.swing.JButton();
        JB_Verde = new javax.swing.JButton();
        JB_Azul = new javax.swing.JButton();
        Eti2 = new javax.swing.JLabel();
        Eti3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PRACTICA 1");
        setBackground(new java.awt.Color(0, 255, 0));
        setForeground(new java.awt.Color(0, 0, 0));

        Eti1.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        Eti1.setText("HOLA MUNDO ESTO ES UNA ETIQUETA");
        Eti1.setToolTipText("");

        JB_Rojo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        JB_Rojo.setForeground(new java.awt.Color(204, 0, 0));
        JB_Rojo.setText("ROJO");
        JB_Rojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JB_RojoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JB_RojoMouseExited(evt);
            }
        });
        JB_Rojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_RojoActionPerformed(evt);
            }
        });

        JB_Verde.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        JB_Verde.setForeground(new java.awt.Color(0, 204, 0));
        JB_Verde.setText("VERDE");
        JB_Verde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JB_VerdeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JB_VerdeMouseExited(evt);
            }
        });
        JB_Verde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_VerdeActionPerformed(evt);
            }
        });

        JB_Azul.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        JB_Azul.setForeground(new java.awt.Color(0, 0, 255));
        JB_Azul.setText("AZUL");
        JB_Azul.setActionCommand("AZUL");
        JB_Azul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JB_AzulMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JB_AzulMouseExited(evt);
            }
        });
        JB_Azul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB_AzulActionPerformed(evt);
            }
        });

        Eti2.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        Eti2.setText("GERARDO MIGUEL SANCHEZ GARCIA");
        Eti2.setToolTipText("");

        Eti3.setFont(new java.awt.Font("Algerian", 1, 12)); // NOI18N
        Eti3.setText("TECNOLOGICO DE OCOTLAN");
        Eti3.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(JB_Rojo)
                        .addGap(32, 32, 32)
                        .addComponent(JB_Verde)
                        .addGap(29, 29, 29)
                        .addComponent(JB_Azul))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Eti3, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Eti1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Eti2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(Eti1)
                .addGap(8, 8, 8)
                .addComponent(Eti2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Eti3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JB_Rojo)
                    .addComponent(JB_Verde)
                    .addComponent(JB_Azul))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JB_RojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_RojoActionPerformed
        Eti1.setForeground(Color.red);
         Eti2.setForeground(Color.red);
          Eti3.setForeground(Color.red);
    }//GEN-LAST:event_JB_RojoActionPerformed

    private void JB_VerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_VerdeActionPerformed
        Eti1.setForeground(Color.green);
         Eti2.setForeground(Color.green);
          Eti3.setForeground(Color.green);
    }//GEN-LAST:event_JB_VerdeActionPerformed

    private void JB_AzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB_AzulActionPerformed
       Eti1.setForeground(Color.blue);
         Eti2.setForeground(Color.blue);
          Eti3.setForeground(Color.blue);
    }//GEN-LAST:event_JB_AzulActionPerformed

    private void JB_RojoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_RojoMouseEntered
        JB_Rojo.setForeground(Color.magenta);//para cambiar el color del texto del boton al momento de tocarlo
    }//GEN-LAST:event_JB_RojoMouseEntered

    private void JB_RojoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_RojoMouseExited
       JB_Rojo.setForeground(Color.red);//al dejar de tocar el botton regresar al color rojo el texto
       
    }//GEN-LAST:event_JB_RojoMouseExited

    private void JB_VerdeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_VerdeMouseEntered
        JB_Verde.setForeground(Color.yellow);
    }//GEN-LAST:event_JB_VerdeMouseEntered

    private void JB_VerdeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_VerdeMouseExited
        JB_Verde.setForeground(Color.green);
    }//GEN-LAST:event_JB_VerdeMouseExited

    private void JB_AzulMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AzulMouseEntered
        JB_Azul.setForeground(Color.gray);
    }//GEN-LAST:event_JB_AzulMouseEntered

    private void JB_AzulMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JB_AzulMouseExited
       JB_Azul.setForeground(Color.blue);
    }//GEN-LAST:event_JB_AzulMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IHola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IHola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IHola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IHola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IHola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Eti1;
    private javax.swing.JLabel Eti2;
    private javax.swing.JLabel Eti3;
    private javax.swing.JButton JB_Azul;
    private javax.swing.JButton JB_Rojo;
    private javax.swing.JButton JB_Verde;
    // End of variables declaration//GEN-END:variables
}
