/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Juego;

import javax.swing.JOptionPane;

/**
 *
 * @author mi bodega poncitlan
 */
public class Menu extends javax.swing.JFrame {

   
    int tam;
    Imagenes JFImagenes = new Imagenes();
    JF_Tamaño TAMAÑO = new JF_Tamaño();
    Memox juego = new Memox();
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        JBImagenes = new javax.swing.JButton();
        Jugar = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        BTamaño = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setForeground(new java.awt.Color(204, 204, 0));

        JBImagenes.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        JBImagenes.setForeground(new java.awt.Color(0, 204, 153));
        JBImagenes.setText("Imagenes");
        JBImagenes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBImagenesActionPerformed(evt);
            }
        });

        Jugar.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Jugar.setForeground(new java.awt.Color(255, 0, 102));
        Jugar.setText("Jugar");
        Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JugarActionPerformed(evt);
            }
        });

        Salir.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        Salir.setForeground(new java.awt.Color(204, 0, 0));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        BTamaño.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        BTamaño.setForeground(new java.awt.Color(51, 255, 0));
        BTamaño.setText("Tamaño");
        BTamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTamañoActionPerformed(evt);
            }
        });

        jLabel1.setText("INSTRUCCIONES: SELECCIONE UN TAMAÑO, DESPUES SELECCIONE LAS IMAGENES QUE DESEA UTILIZAR POR ULTIMO DE CLICK EN JUGAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Jugar)
                            .addComponent(Salir)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTamaño)
                            .addComponent(JBImagenes))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(BTamaño)
                .addGap(35, 35, 35)
                .addComponent(JBImagenes)
                .addGap(41, 41, 41)
                .addComponent(Jugar)
                .addGap(38, 38, 38)
                .addComponent(Salir)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JugarActionPerformed
    
    juego.Asignar(TAMAÑO.tam,JFImagenes.f);
    juego.Metodo();
    juego.setLocationRelativeTo(null);//para centrar el frame
    juego.setVisible(true);
    
    }//GEN-LAST:event_JugarActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);//para cerrar la aplicacion
    }//GEN-LAST:event_SalirActionPerformed

    private void JBImagenesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBImagenesActionPerformed
            JFImagenes.Asigna(TAMAÑO.tam);
            JFImagenes.setLocationRelativeTo(null);//para centrar e frame
            JFImagenes.setVisible(true);
        
    }//GEN-LAST:event_JBImagenesActionPerformed

    private void BTamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTamañoActionPerformed
        TAMAÑO.setLocationRelativeTo(null);//para centrar e frame
            TAMAÑO.setVisible(true);
    }//GEN-LAST:event_BTamañoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
          
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTamaño;
    private javax.swing.JButton JBImagenes;
    private javax.swing.JButton Jugar;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
