/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica1.pkg7;

import java.awt.Color;
import java.awt.Font;
import javax.swing.JColorChooser;

/**
 *
 * @author mi bodega poncitlan
 */
public class P7 extends javax.swing.JFrame {
JF_Fuente fuente= new JF_Fuente();
JF_Estilo estilo=new JF_Estilo();
Color c;
JF_Tam Tam=new JF_Tam();
    public P7() {
        initComponents();
        this.setLocationRelativeTo(null);//para centrar el frame en la pantalla
        this.setTitle("uso de menus...");//para añadir un titulo al frame
       Font f = new Font("Arial",0,12);
       Eti.setFont(f);
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        Eti = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        F = new javax.swing.JMenu();
        JM_Tipo = new javax.swing.JMenuItem();
        JM_Estilo = new javax.swing.JMenuItem();
        JM_Color = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        JM_Tamaño = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        JM_Previa = new javax.swing.JMenuItem();
        JM_Salir = new javax.swing.JMenuItem();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jMenu1.setText("jMenu1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Eti.setIcon(new javax.swing.ImageIcon("C:\\Users\\mi bodega poncitlan\\Documents\\TEC\\SEMESTRE 4\\TOPICOS AVANZADOS DE PROGRMACION\\UNIDAD 1\\ICONO.png")); // NOI18N
        Eti.setText("HOLAAAAAAAAAAAAA");

        F.setIcon(new javax.swing.ImageIcon("C:\\Users\\mi bodega poncitlan\\Documents\\TEC\\SEMESTRE 4\\TOPICOS AVANZADOS DE PROGRMACION\\UNIDAD 1\\ICONO4.jpg")); // NOI18N
        F.setText("Fuente");

        JM_Tipo.setText("Tipo");
        JM_Tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_TipoActionPerformed(evt);
            }
        });
        F.add(JM_Tipo);

        JM_Estilo.setText("Estilo");
        JM_Estilo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_EstiloActionPerformed(evt);
            }
        });
        F.add(JM_Estilo);

        JM_Color.setText("Color");
        JM_Color.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_ColorActionPerformed(evt);
            }
        });
        F.add(JM_Color);
        F.add(jSeparator1);

        JM_Tamaño.setText("Tamaño");
        JM_Tamaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_TamañoActionPerformed(evt);
            }
        });
        F.add(JM_Tamaño);

        jMenuBar1.add(F);

        jMenu3.setIcon(new javax.swing.ImageIcon("C:\\Users\\mi bodega poncitlan\\Documents\\TEC\\SEMESTRE 4\\TOPICOS AVANZADOS DE PROGRMACION\\UNIDAD 1\\ICONO3.jpg")); // NOI18N
        jMenu3.setText("Archivo");

        JM_Previa.setText("Vista previa");
        JM_Previa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_PreviaActionPerformed(evt);
            }
        });
        jMenu3.add(JM_Previa);

        JM_Salir.setText("Salir");
        JM_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JM_SalirActionPerformed(evt);
            }
        });
        jMenu3.add(JM_Salir);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(Eti)
                .addGap(105, 105, 105))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(120, Short.MAX_VALUE)
                .addComponent(Eti)
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JM_TipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_TipoActionPerformed
     fuente.setLocationRelativeTo(null);//par centrar el frame
     fuente.setVisible(true);//para hacer visible el frame
    }//GEN-LAST:event_JM_TipoActionPerformed

    private void JM_PreviaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_PreviaActionPerformed
    if(c!=null){
        Eti.setForeground(c);//para cambiar el color de la etiqueda por el color alamacenado en c seleccionado en la sentencia anterior
        }
    Font f = new Font(fuente.nom_fte,estilo.est_fte,Eti.getFont().getSize());//guardar en f el nombre la fuente y el tamaño de la etiqueta
    Eti.setFont(f);//para darle a la etiqueta los valores almacenados en f
    }//GEN-LAST:event_JM_PreviaActionPerformed

    private void JM_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_SalirActionPerformed
    System.exit(0);//para cerrar el programa
    }//GEN-LAST:event_JM_SalirActionPerformed

    private void JM_EstiloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_EstiloActionPerformed
     estilo.setLocationRelativeTo(null);//para centrar e frame
     estilo.setVisible(true);   //para hacer visible el frame
    }//GEN-LAST:event_JM_EstiloActionPerformed

    private void JM_ColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_ColorActionPerformed
        c= JColorChooser.showDialog(this,"Seleccione un color",Color.white);//para traer la paleta de colores y seleccionar uno
        
    }//GEN-LAST:event_JM_ColorActionPerformed

    private void JM_TamañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JM_TamañoActionPerformed
    Tam.setLocationRelativeTo(null);//para centrar el frame
    Tam.setVisible(true);//para centrar el frame
    }//GEN-LAST:event_JM_TamañoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Eti;
    private javax.swing.JMenu F;
    private javax.swing.JMenuItem JM_Color;
    private javax.swing.JMenuItem JM_Estilo;
    private javax.swing.JMenuItem JM_Previa;
    private javax.swing.JMenuItem JM_Salir;
    private javax.swing.JMenuItem JM_Tamaño;
    private javax.swing.JMenuItem JM_Tipo;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
