
package Boton;

import java.awt.GridLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class Memox extends javax.swing.JFrame {
JButton[] Btn= new JButton[16];//establece una arreglo de tipo jbutton para almacenar las cartas
        GridLayout gL= new GridLayout();
        int nf,nc;//variables para el numero de cartas y numero de columnas
    public Memox() {
        initComponents();
        this.setLocationRelativeTo(null);
        String ncar=JOptionPane.showInputDialog("4, 8 o 16 cartas");//para dar la opcion de cuantas cartas seleccionar
        int op=Integer.parseInt(ncar);//convierte a entero el nuemro de cartas
        switch (op){
            case 4:{nf=2;nc=2; break;}//lo establece con cutro columnas
            case 8:{nf=4;nc=2; break;}//lo establece con ocho columnas
            case 16:{nf=4;nc=4; break;}//lo establece con 16 columnas
            default: {nf=4;nc=4;break;}//lo establece con 16 columnas por default
        }
        this.setSize(420,420);
        JP1.setSize(nc*100+5*nc,nf*100+5*nf);
        gL.setColumns(nc);//setea el numero de columnas
        gL.setRows(nf);//setea el numero de filas al  layout
        gL.setHgap(5);//deja un espacio de 5 pixeles 
        gL.setVgap(5);//deja un espacio de 5 pixeles
        JP1.setLayout(gL);
        
        for(int j=0; j<(nf*nc);j++){//esteciclo agraga uno a auno los botones selccionado spor el usuario
            Btn[j] = new JButton("Boton"+(j+1));//para asignar el texto del boton
            JP1.add(Btn[j]);//agrega el boton
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JP1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout JP1Layout = new javax.swing.GroupLayout(JP1);
        JP1.setLayout(JP1Layout);
        JP1Layout.setHorizontalGroup(
            JP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        JP1Layout.setVerticalGroup(
            JP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JP1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Memox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Memox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Memox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Memox.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Memox().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JP1;
    // End of variables declaration//GEN-END:variables
}
