
import java.awt.Color;
import javax.swing.JColorChooser;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author mi bodega poncitlan
 */
public class SeleccionarColor extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionarColor
     */
    public SeleccionarColor() {
        initComponents();
        this.setLocationRelativeTo(null);//para central el frame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Botones = new javax.swing.ButtonGroup();
        Eti = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        RbRojo = new javax.swing.JRadioButton();
        RbVerde = new javax.swing.JRadioButton();
        RbAzul = new javax.swing.JRadioButton();
        RbOtro = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Eti.setFont(new java.awt.Font("AR JULIAN", 1, 18)); // NOI18N
        Eti.setText("ETIQUETA");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        Botones.add(RbRojo);
        RbRojo.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        RbRojo.setForeground(new java.awt.Color(204, 0, 0));
        RbRojo.setText("Rojo");
        RbRojo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbRojoActionPerformed(evt);
            }
        });

        Botones.add(RbVerde);
        RbVerde.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        RbVerde.setForeground(new java.awt.Color(102, 255, 0));
        RbVerde.setText("Verde");
        RbVerde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbVerdeActionPerformed(evt);
            }
        });

        Botones.add(RbAzul);
        RbAzul.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        RbAzul.setForeground(new java.awt.Color(0, 0, 255));
        RbAzul.setText("Azul");
        RbAzul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbAzulActionPerformed(evt);
            }
        });

        Botones.add(RbOtro);
        RbOtro.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        RbOtro.setText("Otro");
        RbOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbOtroActionPerformed(evt);
            }
        });

        jButton1.setText("Seleccionar color");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(Eti))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RbAzul)
                            .addComponent(RbVerde)
                            .addComponent(RbRojo)
                            .addComponent(RbOtro)
                            .addComponent(jButton1))))
                .addContainerGap(149, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Eti)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(RbRojo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RbVerde)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RbAzul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RbOtro)
                .addGap(29, 29, 29)
                .addComponent(jButton1)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RbOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbOtroActionPerformed

    }//GEN-LAST:event_RbOtroActionPerformed

    private void RbRojoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbRojoActionPerformed

    }//GEN-LAST:event_RbRojoActionPerformed

    private void RbVerdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbVerdeActionPerformed

    }//GEN-LAST:event_RbVerdeActionPerformed

    private void RbAzulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbAzulActionPerformed

     }//GEN-LAST:event_RbAzulActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (RbAzul.isSelected()) {
            Eti.setForeground(Color.blue);
        }
        if (RbVerde.isSelected()) {
            Eti.setForeground(Color.green);
        }
        if (RbRojo.isSelected()) {
            Eti.setForeground(Color.red);
        }
        if (RbOtro.isSelected()) {

            Color c = JColorChooser.showDialog(this, "Seleccione un color", Color.white);//para traer la paleta de colores y seleccionar uno
            if (c != null) {
                Eti.setForeground(c);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeleccionarColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeleccionarColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeleccionarColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeleccionarColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeleccionarColor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Botones;
    private javax.swing.JLabel Eti;
    private javax.swing.JRadioButton RbAzul;
    private javax.swing.JRadioButton RbOtro;
    private javax.swing.JRadioButton RbRojo;
    private javax.swing.JRadioButton RbVerde;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
