nombre = input('Escribe tu nombre')
apellido =input('Escribe tu apellido')
fechaNacimiento = input('Escribe tu fecha de nacimiento en el formato dd/mm/aaaa')
telefono = input('Escribe tu telefono')
sexo= input('Escribe tu sexo')
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print(format('Los datos leidos son:','^150'))
print(format(nombre, '^150'))
print(format(apellido, '^150'))
print(format(fechaNacimiento, '^150'))
print(format(telefono, '^150'))
print(format(sexo, '^150'))
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
print()
